import turtle
def Peach_heart():
    turtle.color("red")
    turtle.begin_fill()
    turtle.left(135)
    turtle.forward(100)
    turtle.right(180)
    turtle.circle(50,-180)
    turtle.left(90)
    turtle.circle(50,-180)
    turtle.right(180)
    turtle.forward(100)
    turtle.end_fill()

Peach_heart()
turtle.penup()
turtle.goto(100,30)
turtle.pendown()
turtle.setheading(0)
Peach_heart()
turtle.penup()
turtle.goto(-100,30)
turtle.pendown()
turtle.setheading(25)
turtle.pensize(5)
turtle.forward(350)
turtle.done()
